version: '3.9'

services: 
  db:
    container_name: audit_conflict_poc_db
    image: postgres:14.2-alpine
    env_file: '.env'
    ports:
      - '5432:5432'
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh:z
      - ./audit.sql:/docker-entrypoint-initdb.d/audit.sql:z
  db_admin:
    container_name: audit_conflict_poc_db_admin
    image: dpage/pgadmin4:6.7
    env_file: '.env'
    ports:
      - "9090:80"
    logging:
      driver: none
    depends_on: 
      - db